const { buildSync } = require('esbuild');
buildSync({
  entryPoints: ['themes/dungeon/src/theme.js'],
  outfile: 'themes/dungeon/theme.js',
  bundle: true,
  format: 'iife',
  target: ['es2020'],
  supported: { 'template-literal': false },
  minify: true,
  legalComments: 'eof',
  banner: { js: '// Generated by npm run build:dungeon. Edit themes/dungeon/src/ instead.' },
});
